# Generated by Django 4.0.3 on 2022-03-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DP_Project', '0002_alter_knapsack_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=256, verbose_name='操作')),
                ('time', models.DateTimeField(max_length=19, verbose_name='时间')),
            ],
            options={
                'verbose_name': '日志记录',
                'verbose_name_plural': '日志记录',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='knapsack',
            options={'ordering': ('number',), 'verbose_name': '背包数据', 'verbose_name_plural': '背包数据'},
        ),
    ]
