# Generated by Django 4.0.3 on 2022-04-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DP_Project', '0003_logging_alter_knapsack_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='knapsack',
            name='performance',
            field=models.FloatField(default=0.0, verbose_name='性价比'),
        ),
    ]
